# 1.7 INTRODUCTION TO NUMPY 

In [2]:
import numpy as np

### CREATING ARRAYS

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.full(10,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [6]:
a=np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
a[2]

np.int64(3)

In [8]:
a[2]=100
a

array([  1,   2, 100,   4,   5,   6,   7,   8,   9])

In [9]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [10]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

## MULTI-DIMENTIONAL ARRAYS

In [11]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.ones((7,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
m=np.array([
        [2, 6, 8],
        [12, 67, 3],
        [-2, 4, 0],

])

In [14]:
m

array([[ 2,  6,  8],
       [12, 67,  3],
       [-2,  4,  0]])

In [15]:
m[2,2]

np.int64(0)

In [16]:
m[2,1]

np.int64(4)

In [17]:
m[2,1]=1000
m

array([[   2,    6,    8],
       [  12,   67,    3],
       [  -2, 1000,    0]])

In [18]:
m[0]

array([2, 6, 8])

In [19]:
m[:,1]

array([   6,   67, 1000])

In [20]:
m[2,:]

array([  -2, 1000,    0])

In [21]:
m[2]

array([  -2, 1000,    0])

In [22]:
m[2,:]=[100, 200, 300]
m

array([[  2,   6,   8],
       [ 12,  67,   3],
       [100, 200, 300]])

## RANDOMLY GENERATED ARRAYS

In [23]:
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [24]:
30*np.random.rand(2,2)

array([[18.63401498, 15.87426283],
       [ 4.03739836, 15.40734364]])

In [25]:
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [26]:
np.random.seed(2)
np.random.randint(low=3,high=20,size=(4,3))

array([[11, 18, 16],
       [11, 14, 14],
       [11, 10,  5],
       [14, 18,  8]])

## ELEMENT-WISE OPERATIONS

In [27]:
a= np.arange(5)
a

array([0, 1, 2, 3, 4])

In [28]:
a+1

array([1, 2, 3, 4, 5])

In [29]:
a*4

array([ 0,  4,  8, 12, 16])

In [30]:
b=(10-3*a)**2 /4
b

array([25.  , 12.25,  4.  ,  0.25,  1.  ])

In [31]:
a+b

array([25.  , 13.25,  6.  ,  3.25,  5.  ])

In [32]:
a/b + 3

array([ 3.        ,  3.08163265,  3.5       , 15.        ,  7.        ])

In [46]:
a*b

array([ 0.  , 12.25,  8.  ,  0.75,  4.  ])

## COMPARISON OPERATIONS

In [34]:
a

array([0, 1, 2, 3, 4])

In [35]:
a<=3

array([ True,  True,  True,  True, False])

In [36]:
b

array([25.  , 12.25,  4.  ,  0.25,  1.  ])

In [37]:
a<=b

array([ True,  True,  True, False, False])

In [38]:
a[a<=b]

array([0, 1, 2])

## SUMMARIZING OPERATIONS

In [39]:
a

array([0, 1, 2, 3, 4])

In [40]:
a.min()

np.int64(0)

In [41]:
a.min()

np.int64(0)

In [42]:
a.sum()

np.int64(10)

In [43]:
a.mean()

np.float64(2.0)

In [44]:
a.std()

np.float64(1.4142135623730951)