# LINEAR ALGEBRA

In [1]:
import numpy as np 

## VECTOR OPERATIONS 

In [2]:
w = np.array([1,4,6,8])
u = np.array([2,7,10,-6])

In [3]:
2*w

array([ 2,  8, 12, 16])

In [4]:
u+w

array([ 3, 11, 16,  2])

In [5]:
u*w

array([  2,  28,  60, -48])

## MULTIPLICATION 

In [9]:
u.shape[0]

4

In [12]:
def vv_multiplication(u,w):
    assert u.shape[0]==w.shape[0]
    n=u.shape[0]
    
    result=0
    for i in range(n):
        result += u[i]*w[i]

    return result 

In [13]:
vv_multiplication(u,w)

np.int64(42)

In [16]:
v = np.array([1,4,6,8,10])

In [17]:
vv_multiplication(u,v)

AssertionError: 

In [14]:
u.dot(w)

np.int64(42)

In [18]:
M=np.array([
        [2, 6, 8],
        [12, 67, 3],
        [-2, 4, 0],

])

Q=np.array([
        [1, 2, 0],
        [4, -7, 2],
        [2, -1, 0],

])

In [20]:
M.shape

(3, 3)