# LINEAR ALGEBRA

In [148]:
import numpy as np 

## VECTOR OPERATIONS 

In [149]:
w = np.array([1,4,6,8])
u = np.array([2,7,10,-6])

In [150]:
2*w

array([ 2,  8, 12, 16])

In [151]:
u+w

array([ 3, 11, 16,  2])

In [152]:
u*w

array([  2,  28,  60, -48])

## MULTIPLICATION 

In [153]:
u.shape[0]

4

In [154]:
def vv_multiplication(u,w):
    assert u.shape[0]==w.shape[0]
    n=u.shape[0]
    
    result=0
    for i in range(n):
        result += u[i]*w[i]

    return result 

In [155]:
vv_multiplication(u,w)

np.int64(42)

In [156]:
v = np.array([-2,4,6,8])

In [157]:
vv_multiplication(u,v)

np.int64(36)

In [158]:
u.dot(w)

np.int64(42)

In [159]:
M=np.array([
        [2, 6, 8],
        [12, 67, 3],
        [-2, 4, 0],

])

v = np.array([-2,6,8])

In [160]:
M.shape
v.shape

(3,)

In [161]:
def mv_multiplication(M,v):
    assert M.shape[1]==v.shape[0]
    n=M.shape[0]
    
    result=np.zeros(n)

    for i in range(n):
        result[i] = M[i].dot(v)

    return result 

In [162]:
mv_multiplication(M,v)

array([ 96., 402.,  28.])

In [163]:
M.dot(v)

array([ 96, 402,  28])

In [164]:
M=np.array([
        [1, 0, 0],
        [0, 1, 0],
        [0, 0, 1],

])

Q=np.array([
        [1, 2, 0],
        [4, -7, 2],
        [2, -1, 0],

])

In [165]:
def mm_multiplication(M,Q):
    assert M.shape[1]==Q.shape[0]
    n=M.shape[0]
    m=Q.shape[1]

    result=np.zeros([n,m])

    for j in range(m):
        result[:,j] += M.dot(Q[:,j])
    return result 

In [169]:
mm_multiplication(M,Q)

array([[ 1.,  2.,  0.],
       [ 4., -7.,  2.],
       [ 2., -1.,  0.]])

In [175]:
m_id=np.eye(3)

In [178]:
Q.dot(m_id)

array([[ 1.,  2.,  0.],
       [ 4., -7.,  2.],
       [ 2., -1.,  0.]])

In [179]:
Q.dot(m_id)==Q

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [181]:
Q

array([[ 1,  2,  0],
       [ 4, -7,  2],
       [ 2, -1,  0]])

In [184]:
Q_inv=np.linalg.inv(Q)

In [185]:
Q.dot(Q_inv)

array([[ 1.00000000e+00, -1.88737914e-16,  8.88178420e-18],
       [ 0.00000000e+00,  1.00000000e+00, -4.44089210e-18],
       [ 0.00000000e+00, -1.97215226e-31,  1.00000000e+00]])